import sqlite3
import os
import uuid
import json

DB_PATH = os.path.join(os.path.dirname(__file__), "sinylon_studio.db")

RAW_WORKERS_JSON = """[
  {
    "id": 1,
    "uuid": "66e07178-e419-4bb0-a1cb-fd058e82af1b",
    "matricule": "SIN-0032",
    "nom": "Shi",
    "prenom": "Junming",
    "fonction": "Automatisme PLC",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Shi Junming.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:23:32",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 5,
    "uuid": "74463505-a704-46d9-ab60-b5154e0cac69",
    "matricule": "SIN-0036",
    "nom": "Wang",
    "prenom": "Lei",
    "fonction": "Ingénieur Conception",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/WANG LEI.png",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:23:32",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 24,
    "uuid": "48505dbe-6ea1-44a5-9660-62d426ee6627",
    "matricule": "SIN-1038",
    "nom": "Dong Genmiao",
    "prenom": "",
    "fonction": "Interim",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Dong Genmiao.jpg",
    "qr_code_path": null,
    "status": "Inactif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 25,
    "uuid": "fa7f2cc6-9556-466e-a51b-eb9874e8590d",
    "matricule": "SIN-1040",
    "nom": "SunXuekui",
    "prenom": "",
    "fonction": "Ajustement Mécanique",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/SunXuekui.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 26,
    "uuid": "1a882a69-efe0-4a47-b96a-6c7e122823ba",
    "matricule": "SIN-1042",
    "nom": "YuanBo",
    "prenom": "",
    "fonction": "Ajustement Mécanique",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/YuanBo.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 27,
    "uuid": "f3172881-6d1f-4d46-8525-5d90ce3a5af2",
    "matricule": "SIN-1044",
    "nom": "ZhouKaiXuan",
    "prenom": "",
    "fonction": "Ajustement Mécanique",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/ZhouKaiXuan.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 28,
    "uuid": "52e195a0-d114-4b02-9838-35e619a6b19b",
    "matricule": "SIN-1046",
    "nom": "WangZhen",
    "prenom": "",
    "fonction": "Ajustement Mécanique",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/WangZhen.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 29,
    "uuid": "04b34737-5808-4b21-911f-397f32473c76",
    "matricule": "SIN-1048",
    "nom": "ZhangJiaLe",
    "prenom": "",
    "fonction": "Ajustement Mécanique",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/ZhangJiaLe.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 30,
    "uuid": "cf291a31-16a3-4027-97ae-546141ade4cb",
    "matricule": "SIN-1050",
    "nom": "QinChengGang",
    "prenom": "",
    "fonction": "Ajustement Mécanique",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/QinChengGang.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 31,
    "uuid": "4732538d-bbd9-4926-b4cd-d26980ab08ff",
    "matricule": "SIN-1052",
    "nom": "TianJunLing",
    "prenom": "",
    "fonction": "Ajustement Mécanique",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/TianJunLing.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 32,
    "uuid": "c5e8a0d6-2107-4865-ae77-295749a27b8b",
    "matricule": "SIN-1054",
    "nom": "XiongGuangMing",
    "prenom": "",
    "fonction": "Soudeur / Ingénieur Soudage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/XiongGuangMing.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 33,
    "uuid": "dd9df2fd-4fb2-4648-ae80-fc467f481d1c",
    "matricule": "SIN-1056",
    "nom": "ZhangChao",
    "prenom": "",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/ZhangChao.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 34,
    "uuid": "a4d9592c-438e-4da7-bdc0-914cff06f6cf",
    "matricule": "SIN-1058",
    "nom": "ZhangChaoFeng",
    "prenom": "",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/ZhangChaoFeng.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 35,
    "uuid": "b1de33c1-f6c0-4115-a6c7-bbf0473af9f8",
    "matricule": "SIN-1060",
    "nom": "ZhangLeiLei",
    "prenom": "",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/ZhangLeiLei 2.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 36,
    "uuid": "383463ec-67bf-4861-bb3f-4cb808c2d249",
    "matricule": "SIN-1062",
    "nom": "Zhu",
    "prenom": "Guodong",
    "fonction": "Directeur Projet",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Zhu Guodong.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 37,
    "uuid": "7d2d4474-5cfc-4d00-9aeb-cb7c14b55791",
    "matricule": "SIN-1064",
    "nom": "Lu Wei",
    "prenom": "",
    "fonction": "Roboticien",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Lu Wei.jpg",
    "qr_code_path": null,
    "status": "Inactif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 38,
    "uuid": "af813573-36f5-4306-9fe1-737fd3d0f988",
    "matricule": "SIN-1066",
    "nom": "ZhouLin",
    "prenom": "",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/ZHOU lin.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 41,
    "uuid": "b05bdd8e-4fa7-4e06-8220-1398287ada7e",
    "matricule": "SIN-1072",
    "nom": "Yan",
    "prenom": "Jianying",
    "fonction": "Ingénieur Process",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Yan Jianying.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 42,
    "uuid": "5a9879cd-0c4e-4924-9d16-6b886083d28f",
    "matricule": "SIN-1074",
    "nom": "Jiang Guichen",
    "prenom": "",
    "fonction": "Ingénieur Conception",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Jiang Guichen.jpg",
    "qr_code_path": null,
    "status": "Inactif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 44,
    "uuid": "d7f6e3bf-c9fd-4e2c-9086-45c8a262b97b",
    "matricule": "SIN-1078",
    "nom": "ZHAO",
    "prenom": "HAI WA",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Zhao Haiwa.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 45,
    "uuid": "d4f72d2c-8113-478c-9997-f5477ef30880",
    "matricule": "SIN-1080",
    "nom": "Qin",
    "prenom": "Ziyue",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Qin Ziyue.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 46,
    "uuid": "c67384de-445b-40b6-bb3b-dafa262e549c",
    "matricule": "SIN-1082",
    "nom": "Shu",
    "prenom": "Qinghua",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Shu Qinghua.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 47,
    "uuid": "f3a48fc7-6661-4c8e-b9fc-fb379a239fff",
    "matricule": "SIN-1084",
    "nom": "Wang",
    "prenom": "Junpeng",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Wang Junpeng.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 48,
    "uuid": "9f0d2277-fdaf-4026-b4a1-f9d1559d3a08",
    "matricule": "SIN-1086",
    "nom": "Wan",
    "prenom": "Chao",
    "fonction": "Ajustement Mécanique",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Wan  Chao.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 49,
    "uuid": "bcceb928-97d0-46f6-9b65-285ee3ccff46",
    "matricule": "SIN-1088",
    "nom": "ZOU",
    "prenom": "PING",
    "fonction": "Ajustement Mécanique",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Zou Ping.jpg",
    "qr_code_path": null,
    "status": "Inactif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 50,
    "uuid": "74369a77-24f6-464d-9931-e2b7359abf89",
    "matricule": "SIN-1090",
    "nom": "WANG",
    "prenom": "PAN",
    "fonction": "Ingénieur Conception",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Wang Pan.jpg",
    "qr_code_path": null,
    "status": "Inactif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 51,
    "uuid": "f300b6ec-2344-40d4-9e20-99b05b8d69b6",
    "matricule": "SIN-1092",
    "nom": "YAN",
    "prenom": "JIN MAO",
    "fonction": "Électricien",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Yan Jin Mao.jpg",
    "qr_code_path": null,
    "status": "Inactif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 52,
    "uuid": "915fb74b-218f-4401-b363-311ab54924cd",
    "matricule": "SIN-1094",
    "nom": "ZHANG",
    "prenom": "HAO",
    "fonction": "Ingénieur Soudage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Zhang Hao.jpg",
    "qr_code_path": null,
    "status": "Inactif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 53,
    "uuid": "a619804b-e5ad-4e4c-9876-dd887ec48ded",
    "matricule": "SIN-1096",
    "nom": "XIANG",
    "prenom": "LEI",
    "fonction": "Ingénieur Robotique",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Xiang Lei.jpg",
    "qr_code_path": null,
    "status": "Inactif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 54,
    "uuid": "42508114-7a3e-49eb-9879-c51df487a879",
    "matricule": "SIN-1098",
    "nom": "ZHU",
    "prenom": "CHUN YONG",
    "fonction": "Automatisme PLC",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Zhu Chun Yong.jpg",
    "qr_code_path": null,
    "status": "Inactif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 55,
    "uuid": "3fd61c0a-35f1-4dc4-9171-23148c2d1653",
    "matricule": "SIN-1100",
    "nom": "ZHOU",
    "prenom": "LI WEI",
    "fonction": "Ingénieur Électrique",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Zhou Li Wei.jpg",
    "qr_code_path": null,
    "status": "Inactif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 56,
    "uuid": "faabfd2e-4444-4f53-b305-578b110d44f1",
    "matricule": "SIN-1102",
    "nom": "Su",
    "prenom": "Bin",
    "fonction": "Métrologie / Contrôle",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Su Bin.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 57,
    "uuid": "7ca31f82-32ff-4398-afd3-a2abc4328ec0",
    "matricule": "SIN-1104",
    "nom": "Su",
    "prenom": "Bu Chan",
    "fonction": "Ingénieur Robotique",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Su Bu Chan.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 58,
    "uuid": "12833ba4-1dfb-488a-b5e5-0e1fb34296c0",
    "matricule": "SIN-1106",
    "nom": "Zhang",
    "prenom": "Hua Xiong",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Zhang Hua Xiong.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 59,
    "uuid": "e6e5dba8-4aaf-4d09-a178-2a6240ff8bb5",
    "matricule": "SIN-1108",
    "nom": "ZHANG",
    "prenom": "PING",
    "fonction": "Chef de Projet",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Zhang Ping.jpg",
    "qr_code_path": null,
    "status": "Inactif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 60,
    "uuid": "9109b508-0100-4fbf-8a38-defc3dfcbf0e",
    "matricule": "SIN-1110",
    "nom": "chennannan",
    "prenom": "",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/CHENNANNAN.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 61,
    "uuid": "8f634cff-b8ee-437e-aa53-0bf4825cfaac",
    "matricule": "SIN-1112",
    "nom": "LUO",
    "prenom": "BIN",
    "fonction": "Électricien",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/LUOBING.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 62,
    "uuid": "fba837c7-235a-4d3f-9d96-f02a62bbb0ef",
    "matricule": "SIN-1114",
    "nom": "LI XIAO",
    "prenom": "LIN",
    "fonction": "Ingénieur Conception",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/LIXIAOLIN.png",
    "qr_code_path": null,
    "status": "Inactif",
    "created_at": "2026-07-26 11:29:57",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 81,
    "uuid": "6951caa0-e5d4-4864-9138-a8a869fbcf38",
    "matricule": "SIN-1118",
    "nom": "Li",
    "prenom": "Jinchao",
    "fonction": "Automatisme PLC",
    "entreprise": "Sinylon",
    "photo_path": null,
    "qr_code_path": null,
    "status": "Inactif",
    "created_at": "2026-08-02 13:43:23",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 82,
    "uuid": "cb7d14ff-0440-4910-ba9a-b2b136e918d9",
    "matricule": "SIN-1120",
    "nom": "LIU",
    "prenom": "JIAN",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Liu Jian.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-08-02 13:43:23",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 83,
    "uuid": "ea388863-6ae0-4337-a813-d5e30c26c0a7",
    "matricule": "SIN-1122",
    "nom": "WANG",
    "prenom": "ZONG SHENG",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Wang Zongsheng.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-08-02 13:43:23",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 84,
    "uuid": "d14134e8-d0dc-44dd-a47f-2f3213ca4450",
    "matricule": "SIN-1124",
    "nom": "Liu",
    "prenom": "XiaoBang",
    "fonction": "Soudeur / Ingénieur Soudage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Liu XiaoBang.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-08-02 13:43:23",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 85,
    "uuid": "f0cfa6d0-bf3f-4b69-9e7b-1a6ed1003283",
    "matricule": "SIN-1126",
    "nom": "Meng",
    "prenom": "Lijie",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Meng Lijie.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-08-10 10:40:20",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 86,
    "uuid": "e8f49394-b163-4ddd-b80c-979246b7f746",
    "matricule": "SIN-1128",
    "nom": "Ning",
    "prenom": "Shijie",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Ning Shijie.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-08-10 10:40:20",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 87,
    "uuid": "16c35a8f-0b0f-43f5-9c6c-5b4374110396",
    "matricule": "SIN-1130",
    "nom": "Hu",
    "prenom": "Diantong",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/Hu Diantong.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-08-10 10:40:20",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 88,
    "uuid": "51325998-a281-4df9-b631-18f32e1031e6",
    "matricule": "SIN-1132",
    "nom": "YANG",
    "prenom": "PING",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/YANG PING.png",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-08-10 10:40:20",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 89,
    "uuid": "41e81670-dc19-4ec7-ac7e-16089cf9ebb6",
    "matricule": "SIN-1134",
    "nom": "YANG",
    "prenom": "Junpeng",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/YANG  Junpeng.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-08-10 10:40:20",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 90,
    "uuid": "4385c1f2-8177-476d-a393-0ea31473d069",
    "matricule": "SIN-1136",
    "nom": "XIAO",
    "prenom": "JIALAI",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/XIAO JIALAI.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-08-10 10:40:20",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 91,
    "uuid": "f4019c37-ce33-45b1-b4ae-2ab535e2bc6c",
    "matricule": "SIN-1138",
    "nom": "CUI",
    "prenom": "SHUHANG",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/CUI SHUHANG.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-08-10 10:40:20",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 92,
    "uuid": "b2f2f1be-e36a-478e-b073-ff6780ca45f6",
    "matricule": "SIN-1177",
    "nom": "XIE",
    "prenom": "XIAN",
    "fonction": "Installation / Montage",
    "entreprise": "Sinylon",
    "photo_path": "/static/photos/XIE XIAN.jpg",
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-08-12 16:13:43",
    "societe_affichee": "Sinylon",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  },
  {
    "id": 95,
    "uuid": "eddd62c0-6b80-45f6-9599-2adb03eab3a4",
    "matricule": "SIN-9999",
    "nom": "TEST",
    "prenom": "Korti",
    "fonction": "Ingénieur Qualité HSE",
    "entreprise": "SINYLON",
    "photo_path": null,
    "qr_code_path": null,
    "status": "Actif",
    "created_at": "2026-08-13 16:17:06",
    "societe_affichee": "SINYLON",
    "projet": "CSPS Projet FIAT",
    "annee": "2026",
    "date_naissance": null,
    "groupe_sanguin": null,
    "cnas": null,
    "carte_id": null,
    "telephone": null,
    "departement": null,
    "entreprise_id": 1,
    "date_emission": "2026-01-01",
    "date_expiration": "2026-12-31",
    "step_1_valide": 1,
    "step_2_valide": 1,
    "step_3_valide": 0,
    "habilitation_hauteur": 0,
    "habilitation_soudure": 0,
    "habilitation_electricite": 0,
    "habilitation_confine": 0,
    "habilitation_engins": 0,
    "habilitation_chimique": 0,
    "habilitation_sst": 0,
    "habilitation_safety": 1,
    "is_blocked": 0,
    "motif_blocage": null,
    "habilitations": null
  }
]"""
OFFICIAL_WORKERS = json.loads(RAW_WORKERS_JSON)

def init_db():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS workers (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            uuid TEXT UNIQUE NOT NULL,
            matricule TEXT UNIQUE NOT NULL,
            nom TEXT NOT NULL,
            prenom TEXT NOT NULL,
            fonction TEXT NOT NULL,
            entreprise TEXT DEFAULT 'Sinylon',
            societe_affichee TEXT DEFAULT 'Sinylon',
            projet TEXT DEFAULT 'CSPS Projet FIAT',
            annee TEXT DEFAULT '2026',
            date_naissance TEXT,
            groupe_sanguin TEXT,
            cnas TEXT,
            carte_id TEXT,
            telephone TEXT,
            departement TEXT,
            entreprise_id INTEGER DEFAULT 1,
            date_emission TEXT DEFAULT '2026-01-01',
            date_expiration TEXT DEFAULT '2026-12-31',
            step_1_valide INTEGER DEFAULT 1,
            step_2_valide INTEGER DEFAULT 1,
            step_3_valide INTEGER DEFAULT 0,
            habilitation_hauteur INTEGER DEFAULT 0,
            habilitation_soudure INTEGER DEFAULT 0,
            habilitation_electricite INTEGER DEFAULT 0,
            habilitation_confine INTEGER DEFAULT 0,
            habilitation_engins INTEGER DEFAULT 0,
            habilitation_chimique INTEGER DEFAULT 0,
            habilitation_sst INTEGER DEFAULT 0,
            habilitation_safety INTEGER DEFAULT 1,
            is_blocked INTEGER DEFAULT 0,
            motif_blocage TEXT,
            photo_path TEXT,
            qr_code_path TEXT,
            status TEXT DEFAULT 'Actif',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS entreprises (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            nom TEXT NOT NULL,
            couleur TEXT DEFAULT '#1d664f',
            couleur_fond TEXT DEFAULT '#111828',
            email_notifications TEXT
        )
    """)

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS print_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            worker_id INTEGER,
            type_impression TEXT DEFAULT 'Badge Individuel',
            printed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (worker_id) REFERENCES workers (id)
        )
    """)

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS permits (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            ref_num TEXT UNIQUE NOT NULL,
            type_permis TEXT NOT NULL,
            entreprise TEXT DEFAULT 'Sinylon',
            demandeur TEXT NOT NULL,
            zone TEXT NOT NULL,
            description TEXT,
            vent_kmh REAL DEFAULT 0,
            temp_celsius REAL DEFAULT 0,
            status TEXT DEFAULT 'VALIDE',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS forms_generated (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            ref_num TEXT NOT NULL,
            type_fiche TEXT NOT NULL,
            titre TEXT NOT NULL,
            demandeur TEXT,
            pdf_path TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # Insert or update all official workers
    for w in OFFICIAL_WORKERS:
        mat = w.get('matricule')
        u = w.get('uuid') or str(uuid.uuid4())
        existing = cursor.execute('SELECT id FROM workers WHERE UPPER(matricule) = UPPER(?) OR uuid = ?', (mat, u)).fetchone()
        if not existing:
            cursor.execute('''
                INSERT INTO workers (
                    uuid, matricule, nom, prenom, fonction, entreprise, societe_affichee,
                    projet, annee, date_naissance, groupe_sanguin, cnas, carte_id,
                    telephone, departement, entreprise_id, date_emission, date_expiration,
                    step_1_valide, step_2_valide, step_3_valide, is_blocked, motif_blocage,
                    photo_path, status
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ''', (
                u, mat, w.get('nom'), w.get('prenom'), w.get('fonction'),
                w.get('entreprise') or 'Sinylon', w.get('societe_affichee') or 'Sinylon',
                w.get('projet') or 'CSPS Projet FIAT', w.get('annee') or '2026',
                w.get('date_naissance'), w.get('groupe_sanguin'), w.get('cnas'),
                w.get('carte_id'), w.get('telephone'), w.get('departement'),
                w.get('entreprise_id') or 1, w.get('date_emission') or '2026-01-01',
                w.get('date_expiration') or '2026-12-31',
                w.get('step_1_valide', 1), w.get('step_2_valide', 1), w.get('step_3_valide', 0),
                w.get('is_blocked', 0), w.get('motif_blocage'),
                w.get('photo_path'), w.get('status') or 'Actif'
            ))

    if cursor.execute('SELECT COUNT(*) FROM entreprises').fetchone()[0] == 0:
        entreprises_data = [
            ('SINYLON CHANTIER FIAT', '#1d664f', '#111828'),
            ('AMCE CONSTRUCTION', '#3b82f6', '#111828'),
            ('STELLANTIS ALGERIE', '#8b5cf6', '#111828'),
            ('CSPS SECURITE', '#ef4444', '#111828')
        ]
        for nom, col, bg in entreprises_data:
            cursor.execute('INSERT INTO entreprises (nom, couleur, couleur_fond) VALUES (?, ?, ?)', (nom, col, bg))

    conn.commit()
    conn.close()
    print('Database initialized with 51 official workers.')

if __name__ == '__main__':
    init_db()